field: f7b2f612-da3a-4044-9230-47616d46e132 # Kerotec Content
fieldLayouts:
  5e20512f-8d45-4bf7-913c-21d854d22b99:
    tabs:
      -
        elements:
          -
            fieldUid: 501e8a5c-932c-4e25-b2c6-7dfb53db6e41 # Intro
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 851e7b15-fc39-48e5-b7d5-ac9644bd6d43 # Thanks Page
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  501e8a5c-932c-4e25-b2c6-7dfb53db6e41: # Intro
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemIntro
    instructions: ''
    name: Intro
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  851e7b15-fc39-48e5-b7d5-ac9644bd6d43: # Thanks Page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemThanksPage
    instructions: ''
    name: 'Thanks Page'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:29159395-d6dc-45e5-aa30-5347f769d03d' # Pages KEROTEC
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: typeForm
name: Form
sortOrder: 5
