field: dd47c6f3-2579-4634-a86b-44112604b851 # aK Content
fieldLayouts:
  06a2ff7a-bf7d-4d4a-9514-159578119896:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1d513fa9-1b15-46d1-97b0-6f0f08cb9bbd # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f03bd369-6460-4e1f-8bc0-71a1594a2f38
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7d3e7019-ebcc-439f-a8dd-12f751b17a7e # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68307cd0-dd4a-4ba1-bd0c-997965fe352b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ce10a31-a493-4465-bb46-b89b1880fee1 # Form
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c07aab11-9027-40fe-a48c-705618587567
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: acaf15e0-f581-4b80-9788-2cf1df6818ee
        userCondition: null
fields:
  1ce10a31-a493-4465-bb46-b89b1880fee1: # Form
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemForm
    instructions: null
    name: Form
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: true
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'template:1'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
  1d513fa9-1b15-46d1-97b0-6f0f08cb9bbd: # Title
    columnSuffix: xtduuizr
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Title.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  7d3e7019-ebcc-439f-a8dd-12f751b17a7e: # Intro
    columnSuffix: eaxtkenn
    contentColumnType: text
    fieldGroup: null
    handle: itemIntro
    instructions: null
    name: Intro
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: typeForm
name: Form
sortOrder: 6
