field: f7b2f612-da3a-4044-9230-47616d46e132 # Kerotec Content
fieldLayouts:
  5e20512f-8d45-4bf7-913c-21d854d22b99:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 501e8a5c-932c-4e25-b2c6-7dfb53db6e41 # Intro
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6065bd8-70ff-4d38-b42e-e2854b4fb994
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 851e7b15-fc39-48e5-b7d5-ac9644bd6d43 # Thanks Page
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 079b34ae-2f51-45b0-8ac2-764f2dc0c854
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 69570086-011c-4e19-a159-8744716e0db3
        userCondition: null
fields:
  501e8a5c-932c-4e25-b2c6-7dfb53db6e41: # Intro
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemIntro
    instructions: null
    name: Intro
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  851e7b15-fc39-48e5-b7d5-ac9644bd6d43: # Thanks Page
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemThanksPage
    instructions: null
    name: 'Thanks Page'
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:29159395-d6dc-45e5-aa30-5347f769d03d' # Pages KEROTEC
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: typeForm
name: Form
sortOrder: 5
