field: dd47c6f3-2579-4634-a86b-44112604b851 # aK Content
fieldLayouts:
  a43db0d8-b722-4533-8e39-335952fecef8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d0d38edf-4c1c-4adb-8f66-74e7bd8999ba # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 285ac5b6-7877-4ace-988b-762c1c0545a5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 09001b44-38ee-4df8-b306-1f7e833d64a3 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6db0515-4747-4f31-9507-26c009491d69
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: a0c54731-967f-41e9-b5f1-dd8a24a0eaca # Accordion List
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30dd5043-7632-439e-8084-c78cd5e0db46
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7ca11670-2a02-45bf-8860-e75bb27834a6
        userCondition: null
fields:
  09001b44-38ee-4df8-b306-1f7e833d64a3: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemImage
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:d21b4646-668b-477d-b8bd-0b619d836508' # Images AK
      defaultUploadLocationSubpath: Accordion-Image
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:d21b4646-668b-477d-b8bd-0b619d836508' # Images AK
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:d21b4646-668b-477d-b8bd-0b619d836508' # Images AK
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a0c54731-967f-41e9-b5f1-dd8a24a0eaca: # Accordion List
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemList
    instructions: null
    name: 'Accordion List'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1360146399
      columns:
        __assoc__:
          -
            - 8e4ea5fe-b25a-4e8b-99b9-810b231cf066 # Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 713c40f9-6659-4eb7-98d8-943cfa224d0b # Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_14_itemlist}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  d0d38edf-4c1c-4adb-8f66-74e7bd8999ba: # Title
    columnSuffix: jfgwirqg
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Title.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: typeAccordionImage
name: 'Accordion / Image'
sortOrder: 6
