field: dd47c6f3-2579-4634-a86b-44112604b851 # aK Content
fieldLayouts:
  7ca2d6d2-5aa8-487d-87cb-8f98deed35f6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d136c00b-5a53-42e5-9b09-7cd30f704c64 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aa40681-4055-4709-9e0c-b6739089ec5d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 35701230-eae9-4b28-a551-db1c2381ad65
        userCondition: null
fields:
  d136c00b-5a53-42e5-9b09-7cd30f704c64: # Text
    columnSuffix: nhpsxrka
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: typeText
name: Text
sortOrder: 2
