field: dd47c6f3-2579-4634-a86b-44112604b851 # aK Content
fieldLayouts:
  4f8230a9-b54e-4163-8a1d-fc1fcf45fb4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 66e1fced-0bd0-4780-af2f-5e29d1db66e7 # Cta
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1bce8707-8c66-4d27-9ade-a2a964133f00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 28b626c1-f2a3-48c7-b858-920b975eb92f
        userCondition: null
fields:
  66e1fced-0bd0-4780-af2f-5e29d1db66e7: # Cta
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemCta
    instructions: null
    name: Cta
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:486d6ce3-ea2f-4adc-b36e-485764691fa3' # aK Cta
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: typeCta
name: Cta
sortOrder: 4
