field: dd47c6f3-2579-4634-a86b-44112604b851 # aK Content
fieldLayouts:
  1fd4cffc-d3d2-48f9-8bda-a0a31c5ff79a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 47e0d4b9-cda8-4353-b888-56e7d00e7126 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9819af6-8181-4ced-a550-a89e8ddbd558
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a19b894-b243-4e76-a249-6602c5b5a90d # Left Column
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b553c9c-dda3-40e0-8ed6-91632150fbe7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 71b63819-458c-4da8-a4f3-b417bed19e90 # Right Column
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 342c7d4e-8c56-4017-9ab3-52510f8bdb45
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4ad06d6-30ff-410d-bb81-c1ea7227dd84 # Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c89a732-b7f0-4e4b-9cd6-1b8eb27eb590
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: b12d2eaf-dc10-4813-acef-cf21718b41dc
        userCondition: null
fields:
  0a19b894-b243-4e76-a249-6602c5b5a90d: # Left Column
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemLeftColumn
    instructions: null
    name: 'Left Column'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1290423859
      columns:
        __assoc__:
          -
            - 6a3e1418-ce26-4ddc-ac39-c59aff8fed94 # Text
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 2830461d-5863-4055-a122-8d114a5fc2da # Link
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_11_itemleftcolumn}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: true
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  47e0d4b9-cda8-4353-b888-56e7d00e7126: # Title
    columnSuffix: eawnwugz
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 1
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  71b63819-458c-4da8-a4f3-b417bed19e90: # Right Column
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemRightColumn
    instructions: null
    name: 'Right Column'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 789851518
      columns:
        __assoc__:
          -
            - c572752c-6407-4ce5-9d56-3cc22352646c # Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 77b39d19-3553-4a62-9302-c3ccf418e7dd # Text
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_11_itemrightcolumn}}'
      fieldLayout: row
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: true
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a4ad06d6-30ff-410d-bb81-c1ea7227dd84: # Video
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemVideo
    instructions: null
    name: Video
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - MP4
      defaultUploadLocationSource: 'volume:0f16953f-3305-4d08-a2fc-8111aa0504e6' # Videos Ak
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:d21b4646-668b-477d-b8bd-0b619d836508' # Images AK
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:0f16953f-3305-4d08-a2fc-8111aa0504e6' # Videos Ak
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: typeTextColumns
name: 'Text Columns'
sortOrder: 2
