field: f7b2f612-da3a-4044-9230-47616d46e132 # Kerotec Content
fieldLayouts:
  df4aa729-bb29-4800-9392-c5313288fb18:
    tabs:
      -
        elements:
          -
            fieldUid: 6eb16d71-fd69-4587-8d3c-56a87696049e # Cta
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f4a44e6-2104-45c9-a348-781fc2e32991 # Background Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  6eb16d71-fd69-4587-8d3c-56a87696049e: # Cta
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemCta
    instructions: ''
    name: Cta
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:0e29d1e7-3766-416c-a6aa-f559b86928a2' # Kerotec CTA
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  7f4a44e6-2104-45c9-a348-781fc2e32991: # Background Color
    columnSuffix: ycdslwyv
    contentColumnType: string
    fieldGroup: null
    handle: itemBackgroundColor
    instructions: ''
    name: 'Background Color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Choose a color'
            -
              - value
              - ''
            -
              - disabled
              - true
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
        -
          __assoc__:
            -
              - label
              - 'Light Yellow'
            -
              - value
              - light
    translationKeyFormat: null
    translationMethod: none
    type: custommodule\fields\BackgroundColor
handle: typeCta
name: Cta
sortOrder: 4
