field: f7b2f612-da3a-4044-9230-47616d46e132 # Kerotec Content
fieldLayouts:
  afcd3567-ef94-42c5-90ab-821352e86148:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8935bcf9-eec9-483e-85c1-d7b96d0f351d # Background Color
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b075b896-3717-4530-89d6-2e9cab90614e
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: d3654845-df5b-4052-8caa-f71df41c0fff
        userCondition: null
fields:
  8935bcf9-eec9-483e-85c1-d7b96d0f351d: # Background Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemBackgroundColor
    instructions: null
    name: 'Background Color'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Choose a color'
            -
              - value
              - ''
            -
              - disabled
              - true
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - dark
    translationKeyFormat: null
    translationMethod: none
    type: custommodule\fields\BackgroundColor
handle: typeUsp
name: USP
sortOrder: 3
