field: f7b2f612-da3a-4044-9230-47616d46e132 # Kerotec Content
fieldLayouts:
  b4e958b6-d4ea-4342-b42d-2457f7f80ffb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9ba41756-ffd1-42e9-a1ab-479d225d4919 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d0fe7bf-7575-4253-992e-ec6cc327de3b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3e7fdee3-0860-47ba-a8cf-516bc6e161dc # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10fb0c65-242b-45da-a6ce-26a9057be47b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: db1862c9-bc64-439c-86a8-cf4335bb24fd # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d48267fa-8333-437b-8f18-31b669aba1ff
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 9027402e-ac14-4c58-9bf5-5893c10fe3d8
        userCondition: null
fields:
  3e7fdee3-0860-47ba-a8cf-516bc6e161dc: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 20378ac5-a6a7-43d3-87a7-a0d9fcd88b44 # Images KEROTEC
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  9ba41756-ffd1-42e9-a1ab-479d225d4919: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Title.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  db1862c9-bc64-439c-86a8-cf4335bb24fd: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemLink
    instructions: null
    name: Link
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - c7c98775-2843-4fd6-b368-8443519e870e # Link
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - e59b830a-0bb1-418a-bb93-e3d8209e4ef3 # Label
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_itemlink}}'
      fieldLayout: row
      maxRows: 1
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: typeText
name: Text
sortOrder: 1
