fieldLayouts:
  0343bd87-251b-4375-a8df-049dd9642d04:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f5d1fec9-9ff7-4f27-8128-76600f775ab7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1441023-555b-45a7-8461-ba6613008258 # Portfolio Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9579ec1-2e9d-49de-a163-b40da648ad75
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 8a6ace62-db4d-4572-9dcb-4cda4d476eee
        userCondition: null
handle: default
hasTitleField: true
name: Standaard
section: 2c01be0c-0ef0-43c7-a7c9-fd3f6a74a10d # Portfolio Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
