fieldLayouts:
  0581287c-adf6-4a6e-9379-523497a37ab2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: default
hasTitleField: true
name: Standaard
section: ae50bcd8-8e12-4e92-9e24-cbf9f0d794d5 # Pages aK
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
