fieldLayouts:
  6e430a78-54b5-4b8f-ad96-225a1529c3e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 425070b1-34b3-476e-8ea2-3b46917dd0a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd47c6f3-2579-4634-a86b-44112604b851 # aK Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbf317fb-53eb-46b7-8dd6-e4725166b962
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 647a254f-de00-4124-b872-9819f956bd2d
        userCondition: null
handle: errorPages
hasTitleField: true
name: 'Error Pages'
section: ae50bcd8-8e12-4e92-9e24-cbf9f0d794d5 # aK Pages
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
