fieldLayouts:
  0b72c7e9-d60e-4ba1-87a9-95802ec074c2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 39546ded-9c49-42f1-93dd-10d03d9ee427 # Home Banner Kero
            instructions: ''
            label: Banner
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: homeKerotec
hasTitleField: false
name: 'Home Kerotec'
section: c5f9eef8-26da-4424-bb7e-34fde589e608 # Home Kerotec
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
