fieldLayouts:
  24d80b58-d2be-440c-9ad8-d6f868eb17f4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1158e50d-231b-40e8-9b14-96d6192ea33b
            warning: null
            width: 100
          -
            fieldUid: dd47c6f3-2579-4634-a86b-44112604b851 # aK Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 103899d2-518c-4fcc-bcbc-98c862670cb2
            warning: null
            width: 100
        name: Inhoud
        uid: 2f6f2931-e347-41fe-9e77-74dd675606c7
handle: legalPages
hasTitleField: true
name: 'Legal Pages'
section: ae50bcd8-8e12-4e92-9e24-cbf9f0d794d5 # aK Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
