defaultPlacement: end
fieldLayouts:
  5589bc77-007d-4353-8e0c-b1f69d8c1608:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 4789beea-a182-4b6d-9ef7-3a1bdb13bc1d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: da642b21-f45b-4456-9422-08fe4f3b8418 # Simple Text
            instructions: null
            label: Text
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a81d0dbf-4f6a-49d3-8d6f-f44d6d415d39
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: dcd9d590-cf17-4cc7-9546-cd098de275d7
        userCondition: null
handle: kerotecServicesCategory
name: 'Kerotec Services Category'
siteSettings:
  9f70fad4-911f-44e3-a43f-fdb17a9dfe38: # Portfolio NL
    hasUrls: false
    template: null
    uriFormat: null
  720b40eb-b03a-414f-9325-147c8050f443: # aK EN
    hasUrls: false
    template: null
    uriFormat: null
  5690ad28-4a4d-4900-b69b-02d69030f2c5: # aK NL
    hasUrls: false
    template: null
    uriFormat: null
  92213a96-10dd-4374-90e8-91000f082c2f: # Kerotec NL
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: dd68fd33-b93f-4f0f-a139-6808ef214d44
