fieldLayouts:
  cb921994-d1ef-4182-b9ae-4fa795582ec9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 6e61eab9-79d4-4364-a362-ee0c5d14c934
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c1180f3e-5591-40a1-a08a-5fb3701f5356 # Standard Image Optimize
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 027344a4-9c49-4b53-8802-3bb7fe77040f
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: cbda29b9-aac1-4d8a-a3d9-8292a8cdcece
        userCondition: null
fs: imagesAkNotAutoResize
handle: imagesAkNotAutoResize
name: 'Images aK Not Auto Resize'
sortOrder: 6
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
