fieldLayouts:
  7f1628ab-2fb1-4d6d-8e6c-6190ab299dfb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Inhoud
        sortOrder: 1
handle: imagesAK
hasUrls: true
name: 'Images AK'
settings:
  bucket: angelokeirsebilck
  contentDisposition: ''
  endpoint: 'https://ams3.digitaloceanspaces.com'
  expires: '15 minutes'
  keyId: $DO_SPACES_API_KEY
  region: ams3
  secret: $DO_SPACES_SECRET
  subfolder: ak/uploads/images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: vaersaagod\dospaces\Volume
url: '@doBaseUrl'
