fieldLayouts:
  424b5dd1-acdd-4291-962a-399bdaec3ecc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 61d56068-5098-4622-b8af-73f6994f6447
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 70d54ec3-f4e9-49e3-90b4-03ea9b42d99d
        userCondition: null
fs: videosAk
handle: videosAk
name: 'Videos Ak'
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
