columnSuffix: null
contentColumnType: string
fieldGroup: 85bcc920-ddf3-4a07-9a21-294989596b05 # aK
handle: fieldAkContent
instructions: null
name: 'aK Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_fieldakcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: siteGroup
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
