columnSuffix: null
contentColumnType: string
fieldGroup: 85bcc920-ddf3-4a07-9a21-294989596b05 # aK
handle: fieldAkFooterNav
instructions: null
name: 'aK Footer Navigation'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 987876381
  contentTable: '{{%stc_fieldakfooternav}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
