columnSuffix: null
contentColumnType: string
fieldGroup: a4c67e6a-9c78-47d7-b3f8-c5e687a624af # Portfolio
handle: fieldPortfolioContent
instructions: ''
name: 'Portfolio Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_fieldportfoliocontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
