columnSuffix: null
contentColumnType: string
fieldGroup: 85bcc920-ddf3-4a07-9a21-294989596b05 # aK
handle: fieldAkHomeBanner
instructions: null
name: 'aK Home Banner'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 2019777246
  columns:
    __assoc__:
      -
        - dd5517ea-70f5-48bf-ab6d-38c6f70ea79d # JS Icos
        -
          __assoc__:
            -
              - width
              - ''
      -
        - ce47be10-c35f-4ff2-b8e6-40055deb9614 # Portrait
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_fieldakhomebanner}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
