columnSuffix: null
contentColumnType: string
fieldGroup: 85bcc920-ddf3-4a07-9a21-294989596b05 # aK
handle: fieldAkContent
instructions: ''
name: 'aK Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_fieldakcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
