columnSuffix: nxsgypia
contentColumnType: string(520)
fieldGroup: af2d83da-9397-4fdd-ae4b-3330cd82854c # KEROTEC
handle: fieldKerotecSeoDescription
instructions: ''
name: 'Kerotec SEO Descripton'
searchable: false
settings:
  byteLimit: null
  charLimit: 130
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
