columnSuffix: yikvytzn
contentColumnType: text
fieldGroup: a4c67e6a-9c78-47d7-b3f8-c5e687a624af # Portfolio
handle: fieldPortfolioHomebannerOptImg
instructions: ''
name: 'Portfolio Homebanner Opt Img'
searchable: false
settings:
  displayDominantColorPalette: '1'
  displayLazyLoadPlaceholderImages: '1'
  displayOptimizedImageVariants: '1'
  variants:
    -
      __assoc__:
        -
          - width
          - '1200'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
