columnSuffix: qujsqybm
contentColumnType: text
fieldGroup: c964ef51-ae37-4a14-aed6-fd8dc72f17e2 # aK Image Optimize
handle: fieldHomeFigureImgOpt
instructions: null
name: 'Home Figure Image Optimize'
searchable: false
settings:
  displayDominantColorPalette: true
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - width
          - '640'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '5'
        -
          - aspectRatioY
          - '8'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '60'
        -
          - format
          - png
    -
      __assoc__:
        -
          - width
          - '550'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - png
    -
      __assoc__:
        -
          - width
          - '470'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - png
    -
      __assoc__:
        -
          - width
          - '375'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '5'
        -
          - aspectRatioY
          - '8'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - png
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
