columnSuffix: oiyccggf
contentColumnType: string
fieldGroup: a4c67e6a-9c78-47d7-b3f8-c5e687a624af # Portfolio
handle: fieldPortfolioHomebanner
instructions: ''
name: 'Portfolio Home Banner'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:bdbc04de-8344-4c00-bdf0-b816a54c869b' # Images Portfolio
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:d21b4646-668b-477d-b8bd-0b619d836508' # Images AK
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:bdbc04de-8344-4c00-bdf0-b816a54c869b' # Images Portfolio
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
