columnSuffix: mprnydzg
contentColumnType: text
fieldGroup: ec9da726-1b22-4a29-9ba2-b6d45638c18c # Common
handle: fieldTel2
instructions: null
name: 'Tel 2'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
