dateModified: 1654712988
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      key: singles
      tableAttributes:
        - link
      type: native
    -
      heading: Content
      type: heading
    -
      key: 'section:0e29d1e7-3766-416c-a6aa-f559b86928a2' # Kerotec CTA
      type: native
    -
      key: 'section:7f5bab1a-0b5c-4d3d-8549-c9a5f32ecfbd' # Kerotec SEO Pages Content
      type: native
    -
      heading: Pages
      type: heading
    -
      key: 'section:ae50bcd8-8e12-4e92-9e24-cbf9f0d794d5' # aK Pages
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      key: 'section:29159395-d6dc-45e5-aa30-5347f769d03d' # Pages KEROTEC
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
        - slug
        - 'field:73565395-0f0b-4846-b8db-e5b9eb2b5ec9' # SEO
      type: native
    -
      key: 'section:5f9e8b14-1faf-4f70-97ae-db745b38d643' # Kerotec SEO Pages
      tableAttributes:
        - postDate
        - expiryDate
        - author
        - link
        - slug
      type: native
    -
      key: 'section:3973a73c-440e-4767-b7a2-967c259a7331' # Legal KEROTEC
      type: native
    -
      heading: ''
      type: heading
    -
      key: 'section:2c01be0c-0ef0-43c7-a7c9-fd3f6a74a10d' # Portfolio Pages
      type: native
    -
      heading: ''
      type: heading
email:
  fromEmail: angelo.keirsebilck1@telenet.be
  fromName: 'AK Craft'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imagesAK:
    hasUrls: true
    name: 'Images AK'
    settings:
      bucket: angelokeirsebilck
      contentDisposition: ''
      endpoint: 'https://ams3.digitaloceanspaces.com'
      expires: '6 months'
      keyId: $DO_SPACES_API_KEY
      region: ams3
      secret: $DO_SPACES_SECRET
      subfolder: ak/uploads/images
    type: vaersaagod\dospaces\Fs
    url: '@doBaseUrl'
  imagesKerotec:
    hasUrls: true
    name: 'Images KEROTEC'
    settings:
      bucket: angelokeirsebilck
      contentDisposition: ''
      endpoint: 'https://ams3.digitaloceanspaces.com'
      expires: '6 months'
      keyId: $DO_SPACES_API_KEY
      region: ams3
      secret: $DO_SPACES_SECRET
      subfolder: kerotec/uploads/images
    type: vaersaagod\dospaces\Fs
    url: '@doBaseUrl'
  imagesPortfolio:
    hasUrls: true
    name: 'Images Portfolio'
    settings:
      bucket: angelokeirsebilck
      contentDisposition: ''
      endpoint: 'https://ams3.digitaloceanspaces.com'
      expires: '6 months'
      keyId: $DO_SPACES_API_KEY
      region: ams3
      secret: $DO_SPACES_SECRET
      subfolder: portfolio/uploads/images
    type: vaersaagod\dospaces\Fs
    url: '@doBaseUrl'
meta:
  __names__:
    0a70e957-2165-4336-99c1-12316a86db89: Services # Services
    0b6cd4f6-3599-4b39-8eaa-6975556e68f1: SubTitle # SubTitle
    0d490fc5-8be5-4e2d-88e6-4dd5a45a558b: 'Text Alignment' # Text Alignment
    0ddcbf11-8b53-4839-b2af-3b18f9581e0a: Preview # Preview
    0e3f5148-d0f0-44ba-982d-4cb08958c9d5: Image # Image
    0e29d1e7-3766-416c-a6aa-f559b86928a2: 'Kerotec CTA' # Kerotec CTA
    1adf90bc-b79b-41e4-90a4-736a424758cc: Link # Link
    1b153723-1ae0-47e2-869c-e118a6c0bbe2: Cta # Cta
    1d3c7a6d-c0e4-4229-928f-7d176da8e6f4: 'Text / Media' # Text / Media
    1d89545b-011e-431b-acd1-d67b21fa253b: 'Kerotec Footer' # Kerotec Footer
    2c01be0c-0ef0-43c7-a7c9-fd3f6a74a10d: 'Portfolio Pages' # Portfolio Pages
    2c532e68-55b9-46e0-8ff3-837835d606c6: 'Background Color' # Background Color
    2cad2871-83ab-4d53-adec-fd96958a90a5: Image # Image
    2f3d4ce1-ea73-40cf-a413-7ddc74c8332e: 'Portfolio Home' # Portfolio Home
    3e7fdee3-0860-47ba-a8cf-516bc6e161dc: Text # Text
    4f2d371f-babc-42bf-9015-c504775f085b: Portfolio # Portfolio
    4fd9f2ab-dfaa-4404-ba4a-47548a90d471: 'Home Kerotec' # Home Kerotec
    5b31df2d-3af7-44b6-88fd-211d07122274: 'Footer Nav' # Footer Nav
    5f9e8b14-1faf-4f70-97ae-db745b38d643: 'Kerotec SEO Pages' # Kerotec SEO Pages
    6d3f9446-799c-4acb-9ab8-d9e11b148b54: Link # Link
    6eb16d71-fd69-4587-8d3c-56a87696049e: Cta # Cta
    6ec2831b-b3c9-47b9-bf52-03beb2b48691: Standaard # Standaard
    6f60c33a-ce18-4d21-bebd-6d53ea16c6d2: 'Portfolio Home' # Portfolio Home
    7ac4ed8e-eb27-4c90-8daf-0a99a4fdd693: Link # Link
    7e74a447-4f0a-4130-b15e-f1df3175e103: Thanks # Thanks
    7f4a44e6-2104-45c9-a348-781fc2e32991: 'Background Color' # Background Color
    7f5bab1a-0b5c-4d3d-8549-c9a5f32ecfbd: 'Kerotec SEO Pages Content' # Kerotec SEO Pages Content
    8b995879-332a-4e28-bb82-eb5b4e3b42e2: Title # Title
    8ed4ac99-1404-4f75-9d5f-6d7454d9e078: Text # Text
    9b95db5c-d503-489b-8025-40c72a236aed: 'Link Label' # Link Label
    9ba41756-ffd1-42e9-a1ab-479d225d4919: Title # Title
    9bd51bcd-1aa8-4def-ae5c-bf2470665d63: Text # Text
    9f70fad4-911f-44e3-a43f-fdb17a9dfe38: 'Portfolio NL' # Portfolio NL
    13a120bf-c8a5-4d82-ac79-ba44d99c869f: Media # Media
    18c36340-3798-4501-b6f0-e3330d5c86d4: References # References
    22dbbbb6-573d-49ad-875c-2a8f8451b7cc: Email # Email
    37b41c08-b9d5-4839-bd5e-1da7203723d3: Link # Link
    56ee6bef-32e6-4203-b7a3-1a99768b2894: Text # Text
    57f24831-8db3-4239-b500-787afe0b7422: 'Kerotec Cta Content' # Kerotec Cta Content
    61ed6125-1194-4538-94b9-9c530f78a246: 'aK Company' # aK Company
    61f15c29-bc3f-4925-bb5d-3da1bf9a8a0d: 'Kerotec Services Category' # Kerotec Services Category
    61f62f82-cbc9-49d8-a8ca-33c3a3b98231: References # References
    64eed068-1f00-44e1-9210-e8ff7f8a693c: 'Portfolio Home Banner' # Portfolio Home Banner
    66f1be27-81fd-4669-9a51-be3292e7462a: Title # Title
    71cad8ae-bad6-4639-a39f-5e54e0bd626b: USP # USP
    73f2882a-d051-4f79-9a5f-624277004d5a: 'Kerotec Navigation' # Kerotec Navigation
    80bdfde6-b6a4-45a2-8d64-45438ba278e0: Standaard # Standaard
    85bcc920-ddf3-4a07-9a21-294989596b05: aK # aK
    86be1713-0ffe-4406-b8ee-4f18b6ea52a0: Label # Label
    98f33ea8-d57c-4bff-bf01-4fef7666c145: Link # Link
    109e1841-623b-4f66-9626-8cfdcf23c016: 'aK Main Navigation' # aK Main Navigation
    181f7be8-f62e-4cb0-869e-fa81544c806c: KEROTEC # KEROTEC
    216a063d-0eac-465e-9a4e-24018fbf1ea9: Intro # Intro
    293c8a21-558c-40da-bae9-ecd978e0a424: 'Background Color' # Background Color
    378bbbf1-f8ba-4c41-874b-c936fea3f11e: 'aK Logo Header' # aK Logo Header
    386ffdca-58d6-49a9-91d0-2a601508dd26: Icon # Icon
    402cf776-37d6-4867-a9cf-44e518322e88: aK # aK
    501e8a5c-932c-4e25-b2c6-7dfb53db6e41: Intro # Intro
    771bfdd2-6549-4fe3-953a-9d5415ecd1f0: Text # Text
    851e7b15-fc39-48e5-b7d5-ac9644bd6d43: 'Thanks Page' # Thanks Page
    914da9e8-cd79-4ed2-81fa-fac242b24f4b: 'Portfolio Main Nav' # Portfolio Main Nav
    3973a73c-440e-4767-b7a2-967c259a7331: 'Legal KEROTEC' # Legal KEROTEC
    5690ad28-4a4d-4900-b69b-02d69030f2c5: 'aK NL' # aK NL
    6081ef70-29ac-4075-a579-f5be60125444: Label # Label
    8935bcf9-eec9-483e-85c1-d7b96d0f351d: 'Background Color' # Background Color
    9559b22c-c5b0-4f50-ae0b-2d627bb0beb6: Title # Title
    20378ac5-a6a7-43d3-87a7-a0d9fcd88b44: 'Images KEROTEC' # Images KEROTEC
    35894e6f-c18b-4f35-8a91-b12f97b81452: Title # Title
    39546ded-9c49-42f1-93dd-10d03d9ee427: 'Home Banner Kerotec' # Home Banner Kerotec
    47142bfd-e33e-4883-ac89-050ffdc2a9cd: 'Public Schema' # Public Schema
    61098cc8-fe0c-42f3-911e-089d747658ff: Image # Image
    91815f01-4d01-4b69-9988-b6fd3e599549: 'Background Color' # Background Color
    92213a96-10dd-4374-90e8-91000f082c2f: 'Kerotec NL' # Kerotec NL
    108034c7-d987-4de8-886e-09d9d92e2496: Text # Text
    4455348d-5047-4b0e-91ae-79e6599d7f6a: Title # Title
    29159395-d6dc-45e5-aa30-5347f769d03d: 'Pages KEROTEC' # Pages KEROTEC
    33773167-d760-4bd1-8da7-270c3802070e: 'Kerotec SEO Descripton' # Kerotec SEO Descripton
    73259272-4635-47f4-8189-da773221ec21: 'Kerotec Company Info' # Kerotec Company Info
    73565395-0f0b-4846-b8db-e5b9eb2b5ec9: SEO # SEO
    a4c67e6a-9c78-47d7-b3f8-c5e687a624af: Portfolio # Portfolio
    a407fca4-ef49-4264-abf2-e0bfb0afb24f: 'Main Nav Highlight' # Main Nav Highlight
    a97918b0-0260-45dc-ad5c-a6289f0f7041: Link # Link
    a1441023-555b-45a7-8461-ba6613008258: 'Portfolio Content' # Portfolio Content
    acb2dfe1-3f16-48b9-ae0f-0923977e23a7: Standaard # Standaard
    ad6e8279-954b-405f-ba63-dce6223d9ebc: 'Kerotec USP' # Kerotec USP
    ae50bcd8-8e12-4e92-9e24-cbf9f0d794d5: 'aK Pages' # aK Pages
    aed1c586-a3d3-4f18-b962-19ef9a594b6a: 'Portfolio Homebanner Opt Img' # Portfolio Homebanner Opt Img
    af2d83da-9397-4fdd-ae4b-3330cd82854c: KEROTEC # KEROTEC
    b1fbd584-8a4a-4b09-9fdf-41aadc84322c: 'aK Highlight Nav' # aK Highlight Nav
    b75a0cb6-184e-43d3-8ef0-7815036e946d: 'aK Home' # aK Home
    b198fce6-3fae-417d-a0ce-c5783705473f: 'Text / Media' # Text / Media
    b92519cf-e415-4f20-af0b-b02eabf460d4: Facebook # Facebook
    b113940c-2a49-456f-b10d-862587b1acda: 'Kerotec SEO Place' # Kerotec SEO Place
    b2332813-5395-4de0-802b-ac483820823b: 'Text / Media' # Text / Media
    bae4c5fc-38f8-4dfc-92ff-0cd99f421e40: 'Portfolio Navigation' # Portfolio Navigation
    bdbc04de-8344-4c00-bdf0-b816a54c869b: 'Images Portfolio' # Images Portfolio
    bfaf1252-6172-43fa-a05b-2bac23a46f4e: 'aK Home' # aK Home
    bfef29c2-5528-446b-a1e1-08dc3b376b65: 'aK Navigation' # aK Navigation
    c5be86d8-4831-4e27-a131-35c7f71d2b04: Link # Link
    c5f9eef8-26da-4424-bb7e-34fde589e608: 'Home Kerotec' # Home Kerotec
    c7c98775-2843-4fd6-b368-8443519e870e: Link # Link
    c8dde2ad-0261-4602-977c-f192e36b6bfb: 'Kerotec Footer Link' # Kerotec Footer Link
    c19c0798-f619-458c-9795-738cd74c4d10: 'Main Nav' # Main Nav
    c39b2c60-002c-4db1-ad99-3e3465d32e19: Image # Image
    c792ad5b-761b-48be-bce6-26b76264a1d7: Title # Title
    c963b7e9-ac8f-47c6-a7eb-2de181771450: 'Kerotec SEO Content' # Kerotec SEO Content
    ca46e5e1-f025-4715-a506-8ec65ef7eaab: Link # Link
    cd364aa4-c870-4611-93ec-f51df6990d5a: Standaard # Standaard
    cf0736f7-9894-4c14-85c7-8f4153818c72: 'Tel 1' # Tel 1
    d21b4646-668b-477d-b8bd-0b619d836508: 'Images AK' # Images AK
    d6037e3b-a18e-4e22-84b7-d7aac2d5c24e: Editor # Editor
    d630936a-542d-48c6-9549-34144ec0a96c: 'Media Position' # Media Position
    da642b21-f45b-4456-9422-08fe4f3b8418: 'Simple Text' # Simple Text
    db1862c9-bc64-439c-86a8-cf4335bb24fd: Link # Link
    db5951dd-5586-44a9-8a0d-ed65d67bf80c: Standaard # Standaard
    dd47c6f3-2579-4634-a86b-44112604b851: 'aK Content' # aK Content
    dfd3ecdb-749b-4fc2-9812-00946dc09d63: Standaard # Standaard
    dffe2681-8efd-46d3-a68a-cc2f9b71cf82: Link # Link
    e00c56a0-9048-4b7f-b5d4-3036129d02f0: Standaard # Standaard
    e8a79905-5681-4a6f-b4f5-d4d52d9063a3: Link # Link
    e59b830a-0bb1-418a-bb93-e3d8209e4ef3: Label # Label
    e70f1d40-fc20-488d-97bb-cb61aec7cc26: Title # Title
    e858e6e9-26e4-4e72-aa50-13999c183bb1: 'Portfolio Default Img Opt' # Portfolio Default Img Opt
    ebb2fbd0-c538-4f49-b238-94b2fc1956d6: Form # Form
    ec9da726-1b22-4a29-9ba2-b6d45638c18c: Common # Common
    ed012596-c927-4b00-9e7d-9fec3eb45f27: Text # Text
    eeb3731d-1450-4343-975c-602a8f77fd79: 'Tel 2' # Tel 2
    f7b2f612-da3a-4044-9230-47616d46e132: 'Kerotec Content' # Kerotec Content
    fbaa787d-4cdf-42fe-9f76-77c086e924e3: Author # Author
    fbd049a5-5396-464a-9c6d-ffc6ffbe7216: 'Kerotec SEO Title' # Kerotec SEO Title
    fd13a2dc-8740-406f-a266-ef3ec9f0f684: 'Kerotec USP' # Kerotec USP
plugins:
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: TXKNV97P3IUTH1J78O993USD
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      capSilhouetteSvgSize: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
                -
                  - unsharpMask
                  - '20'
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
      lowerQualityRetinaImageVariants: true
      sharpenScaledImagePercentage: 50
      transformClass: nystudio107\imageoptimize\imagetransforms\CraftImageTransform
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 8M2SOA5DXRZ6TCZ2GIMFN2VQ
    schemaVersion: 3.0.11
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'AK Craft'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
