dateModified: 1649753069
email:
  fromEmail: angelo.keirsebilck1@telenet.be
  fromName: 'AK Craft'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0ddcbf11-8b53-4839-b2af-3b18f9581e0a: Preview # Preview
    2cad2871-83ab-4d53-adec-fd96958a90a5: Image # Image
    4fd9f2ab-dfaa-4404-ba4a-47548a90d471: 'Home Kerotec' # Home Kerotec
    73f2882a-d051-4f79-9a5f-624277004d5a: Navigation # Navigation
    85bcc920-ddf3-4a07-9a21-294989596b05: aK # aK
    181f7be8-f62e-4cb0-869e-fa81544c806c: KEROTEC # KEROTEC
    216a063d-0eac-465e-9a4e-24018fbf1ea9: Intro # Intro
    402cf776-37d6-4867-a9cf-44e518322e88: aK # aK
    771bfdd2-6549-4fe3-953a-9d5415ecd1f0: Text # Text
    5690ad28-4a4d-4900-b69b-02d69030f2c5: 'aK NL' # aK NL
    9559b22c-c5b0-4f50-ae0b-2d627bb0beb6: Title # Title
    20378ac5-a6a7-43d3-87a7-a0d9fcd88b44: 'Images KEROTEC' # Images KEROTEC
    39546ded-9c49-42f1-93dd-10d03d9ee427: 'Home Banner Kerotec' # Home Banner Kerotec
    47142bfd-e33e-4883-ac89-050ffdc2a9cd: 'Public Schema' # Public Schema
    61098cc8-fe0c-42f3-911e-089d747658ff: Image # Image
    92213a96-10dd-4374-90e8-91000f082c2f: 'Kerotec NL' # Kerotec NL
    4455348d-5047-4b0e-91ae-79e6599d7f6a: Title # Title
    29159395-d6dc-45e5-aa30-5347f769d03d: 'Pages KEROTEC' # Pages KEROTEC
    a407fca4-ef49-4264-abf2-e0bfb0afb24f: 'Main Nav Highlight' # Main Nav Highlight
    ae50bcd8-8e12-4e92-9e24-cbf9f0d794d5: 'Pages aK' # Pages aK
    af2d83da-9397-4fdd-ae4b-3330cd82854c: KEROTEC # KEROTEC
    b198fce6-3fae-417d-a0ce-c5783705473f: 'Text / Media' # Text / Media
    b2332813-5395-4de0-802b-ac483820823b: 'Text / Media' # Text / Media
    c5f9eef8-26da-4424-bb7e-34fde589e608: 'Home Kerotec' # Home Kerotec
    c19c0798-f619-458c-9795-738cd74c4d10: 'Main Nav' # Main Nav
    c39b2c60-002c-4db1-ad99-3e3465d32e19: Image # Image
    c792ad5b-761b-48be-bce6-26b76264a1d7: Title # Title
    ca46e5e1-f025-4715-a506-8ec65ef7eaab: Link # Link
    cd364aa4-c870-4611-93ec-f51df6990d5a: Standaard # Standaard
    d21b4646-668b-477d-b8bd-0b619d836508: 'Images AK' # Images AK
    dd47c6f3-2579-4634-a86b-44112604b851: 'aK Content' # aK Content
    e00c56a0-9048-4b7f-b5d4-3036129d02f0: Standaard # Standaard
    ec9da726-1b22-4a29-9ba2-b6d45638c18c: Common # Common
    f7b2f612-da3a-4044-9230-47616d46e132: 'Kerotec Content' # Kerotec Content
plugins:
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.11
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
system:
  edition: pro
  live: true
  name: 'AK Craft'
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
