field: 109e1841-623b-4f66-9626-8cfdcf23c016 # aK Main Navigation
fieldLayouts:
  be4603de-0d74-41ed-8cc4-57c637c5b4c9:
    tabs:
      -
        elements:
          -
            fieldUid: c5be86d8-4831-4e27-a131-35c7f71d2b04 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9d03c06-ec34-4345-be98-ab06ed15a19d
            warning: null
            width: 100
        name: Content
        uid: 3afc1919-5c87-400f-bc2e-33f52dbd57bd
fields:
  c5be86d8-4831-4e27-a131-35c7f71d2b04: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: false
        email:
          allowAliases: false
          disableValidation: false
          enabled: false
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: false
        url:
          allowAliases: false
          disableValidation: false
          enabled: false
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: site
    type: lenz\linkfield\fields\LinkField
