field: bd8a53d4-23ba-4940-8ce4-fe197eaee782 # aK Usp Content
fieldLayouts:
  7c1c4520-1758-4ff0-aba9-662e4fe7774c:
    tabs:
      -
        elements:
          -
            fieldUid: 292de821-3f7e-401a-aacb-cd0c9eab1022 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebdb8ca9-dbd3-4ec5-8eec-e752b2e977af
            warning: null
            width: 100
        name: Content
        uid: 8d4846c3-9ab3-46f6-bf41-0ce979b0a8e8
fields:
  292de821-3f7e-401a-aacb-cd0c9eab1022: # Text
    columnSuffix: dupwlzhz
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes:
        - d21b4646-668b-477d-b8bd-0b619d836508 # Images AK
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
