field: a0c54731-967f-41e9-b5f1-dd8a24a0eaca # Accordion List
fieldLayouts:
  ba372e18-bfcf-4d61-94f3-f4d0fe81aa9b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8e4ea5fe-b25a-4e8b-99b9-810b231cf066 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf3ce40a-1cb1-4e7b-871b-7a5826026d27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 713c40f9-6659-4eb7-98d8-943cfa224d0b # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c385266-0ca8-4409-9a3f-bb7fbcda13d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8a3e74b8-c557-4c40-a20e-e326d7d6a303
        userCondition: null
fields:
  8e4ea5fe-b25a-4e8b-99b9-810b231cf066: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  713c40f9-6659-4eb7-98d8-943cfa224d0b: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
