field: 71b63819-458c-4da8-a4f3-b417bed19e90 # Right Column
fieldLayouts:
  49e95684-3fac-41b5-a669-69768e0041fd:
    tabs:
      -
        elements:
          -
            fieldUid: c572752c-6407-4ce5-9d56-3cc22352646c # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71791dca-38e4-4335-a258-e8f035ee3218
            warning: null
            width: 100
          -
            fieldUid: a607b8a6-e61c-47cc-b593-f34192c7d9a7 # Show Party Icon
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a3a23e8-a684-4fe0-9a2b-d32d577f1405
            warning: null
            width: 100
          -
            fieldUid: 77b39d19-3553-4a62-9302-c3ccf418e7dd # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28677456-ce9c-4d82-a4ff-10012d461788
            warning: null
            width: 100
          -
            fieldUid: 602b45f2-9a9d-4b49-b368-c0eddd131c82
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1af0197f-8414-489e-9690-286be1c049f0
            warning: null
            width: 100
        name: Content
        uid: 97b19736-0ac3-4bf1-b514-dc4180ad1283
fields:
  77b39d19-3553-4a62-9302-c3ccf418e7dd: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  602b45f2-9a9d-4b49-b368-c0eddd131c82:
    columnSuffix: ituzbnou
    contentColumnType: boolean
    fieldGroup: null
    handle: itemArrowDown
    instructions: null
    name: 'Show Arrow Down'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a607b8a6-e61c-47cc-b593-f34192c7d9a7: # Show Party Icon
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: itemShowIcon
    instructions: null
    name: 'Show Party Icon'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c572752c-6407-4ce5-9d56-3cc22352646c: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 1
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
