field: 71b63819-458c-4da8-a4f3-b417bed19e90 # Right Column
fieldLayouts:
  49e95684-3fac-41b5-a669-69768e0041fd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c572752c-6407-4ce5-9d56-3cc22352646c # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ae1de9f-d6a3-431f-92fa-b2d47580802c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77b39d19-3553-4a62-9302-c3ccf418e7dd # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c6bc113-8f9e-404c-9f9d-ac5a304d7744
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 97b19736-0ac3-4bf1-b514-dc4180ad1283
        userCondition: null
fields:
  77b39d19-3553-4a62-9302-c3ccf418e7dd: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  c572752c-6407-4ce5-9d56-3cc22352646c: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Title.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
