field: 71b63819-458c-4da8-a4f3-b417bed19e90 # Right Column
fieldLayouts:
  49e95684-3fac-41b5-a669-69768e0041fd:
    tabs:
      -
        elements:
          -
            fieldUid: c572752c-6407-4ce5-9d56-3cc22352646c # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f45604ce-e34c-4c55-ac53-cfee74192c05
            warning: null
            width: 100
          -
            fieldUid: 77b39d19-3553-4a62-9302-c3ccf418e7dd # Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4fa9762-f37b-463f-b412-3b6a1b71cfff
            warning: null
            width: 100
        name: Content
        uid: 97b19736-0ac3-4bf1-b514-dc4180ad1283
fields:
  77b39d19-3553-4a62-9302-c3ccf418e7dd: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  c572752c-6407-4ce5-9d56-3cc22352646c: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 1
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
