field: 57f24831-8db3-4239-b500-787afe0b7422 # Kerotec Cta Content
fieldLayouts:
  18d8e553-824b-41f3-aae0-c40ae648b829:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8b995879-332a-4e28-bb82-eb5b4e3b42e2 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e849cd4-77f0-4f5d-b776-92e67533cfb4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0e3f5148-d0f0-44ba-982d-4cb08958c9d5 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ef29bb2-b870-44f2-b50c-d4e085b78566
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed012596-c927-4b00-9e7d-9fec3eb45f27 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd3622ff-cd27-4885-8c37-c905ddbae022
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1adf90bc-b79b-41e4-90a4-736a424758cc # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3d55264-8756-413c-96f0-5904b14afb9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b95db5c-d503-489b-8025-40c72a236aed # Link Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45107b67-56ad-4655-b79f-8daede0471a1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c672c109-de55-4c49-a189-987f258eb1a6
        userCondition: null
fields:
  0e3f5148-d0f0-44ba-982d-4cb08958c9d5: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemImage
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:20378ac5-a6a7-43d3-87a7-a0d9fcd88b44' # Images KEROTEC
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:d21b4646-668b-477d-b8bd-0b619d836508' # Images AK
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:20378ac5-a6a7-43d3-87a7-a0d9fcd88b44' # Images KEROTEC
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  1adf90bc-b79b-41e4-90a4-736a424758cc: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemLink
    instructions: null
    name: Link
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:29159395-d6dc-45e5-aa30-5347f769d03d' # Pages KEROTEC
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  8b995879-332a-4e28-bb82-eb5b4e3b42e2: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 1
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  9b95db5c-d503-489b-8025-40c72a236aed: # Link Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemLinkLabel
    instructions: null
    name: 'Link Label'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  ed012596-c927-4b00-9e7d-9fec3eb45f27: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
