field: 5b31df2d-3af7-44b6-88fd-211d07122274 # Footer Nav
fieldLayouts:
  c833e978-98ab-41e0-b930-cb19f5f131b5:
    tabs:
      -
        elements:
          -
            fieldUid: e8a79905-5681-4a6f-b4f5-d4d52d9063a3 # Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  e8a79905-5681-4a6f-b4f5-d4d52d9063a3: # Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemLink
    instructions: ''
    name: Link
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:29159395-d6dc-45e5-aa30-5347f769d03d' # Pages KEROTEC
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
