fieldLayouts:
  647de0e4-b480-464f-9936-ddbc31285cf0:
    tabs:
      -
        elements:
          -
            fieldUid: 109e1841-623b-4f66-9626-8cfdcf23c016 # aK Main Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12d7a456-1cf8-4bd3-9047-2cf62b555428
            warning: null
            width: 100
          -
            fieldUid: a407fca4-ef49-4264-abf2-e0bfb0afb24f # Main Nav Highlight
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84bde8e6-b392-415b-a8c3-e2387963df35
            warning: null
            width: 100
        name: Main
        uid: 66d88879-ff94-4127-a763-8111b65edb5f
handle: akNavigation
name: 'aK Navigation'
sortOrder: 7
