fieldLayouts:
  647de0e4-b480-464f-9936-ddbc31285cf0:
    tabs:
      -
        elements:
          -
            fieldUid: 109e1841-623b-4f66-9626-8cfdcf23c016 # aK Main Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12d7a456-1cf8-4bd3-9047-2cf62b555428
            warning: null
            width: 100
          -
            fieldUid: b1fbd584-8a4a-4b09-9fdf-41aadc84322c # aK Highlight Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 780b0ecd-5e32-4dba-aabb-fc76577c524d
            warning: null
            width: 100
        name: Main
        uid: 66d88879-ff94-4127-a763-8111b65edb5f
handle: globalAkNav
name: 'aK Navigation'
sortOrder: 7
