fieldLayouts:
  efdca61e-dbf3-47ec-aa41-91ecb5da2072:
    tabs:
      -
        elements:
          -
            fieldUid: ad6e8279-954b-405f-ba63-dce6223d9ebc # Kerotec USP
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: globalUspKerotec
name: 'USP Kerotec'
sortOrder: 2
