fieldLayouts:
  b934d781-80d3-439f-a223-5e240a86792c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c8dde2ad-0261-4602-977c-f192e36b6bfb # Kerotec Footer Link
            instructions: null
            label: 'Footer Link'
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab8d9238-5fc3-452d-97ee-64ac8c71fc16
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 526b0991-4d97-4e80-8b18-03651fed51d4
        userCondition: null
handle: globalKerotecFooter
name: 'Kerotec Footer'
sortOrder: 4
