defaultPlacement: end
enableVersioning: true
handle: AkPages
name: 'aK Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: siteGroup
siteSettings:
  720b40eb-b03a-414f-9325-147c8050f443: # aK EN
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{slug}'
  5690ad28-4a4d-4900-b69b-02d69030f2c5: # aK NL
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: cd39b00f-3916-43a9-a66b-9ed2acbb3866
type: structure
