defaultPlacement: end
enableVersioning: true
handle: AkPages
name: 'aK Pages'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5690ad28-4a4d-4900-b69b-02d69030f2c5: # aK NL
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{slug}'
type: channel
